export default {
    access_token: '',
    token_type: 'Bearer',
    expires_at: '',
    isLoggedIn: '',
    user: {},
    coordenates: {
        latitude: '',
        longitude: ''
    },
    code: 0,
    codeArray: [],
    package: {},
    bag: {},
    clientes: {},
    remitente:{},
    destinatario:{},
    remitenteBag:{},
    destinatarioBag:{},
    tipos: [],
    tipo: {},
    image: '',
    agencias: [],
    agencia: {},
    secciones: [],
    seccion: {},
    transito: '',
    bagPackage: [],

}